# Generated by Django 3.2 on 2022-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('international_code', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
