# Generated by Django 3.2 on 2022-08-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
